# Generated by Django 4.1.3 on 2022-11-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id', 'email')},
        ),
    ]
