# Generated by Django 4.1.3 on 2022-11-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
