# Generated by Django 4.1.3 on 2023-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantiy',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
