# Generated by Django 4.1.3 on 2022-11-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Xác nhận đơn hàng', 'Xác nhận đơn hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Giao hàng thành công', 'Giao hàng thành công')], default='Đang chờ xác nhận', max_length=50),
        ),
    ]
