# Generated by Django 4.1.3 on 2023-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Đã xác nhận đơn hàng', 'Đã xác nhận đơn hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Giao hàng thành công', 'Giao hàng thành công')], default='Đang chờ xác nhận', max_length=50),
        ),
    ]
